---
- hosts: all
  become_user: root
  tasks:
        - name: Ensure download directory is present
          file: path={{ ansible_env.HOME }}/nagios state=directory

        - name: Install Nagios prerequisites for Ubuntu
          apt: pkg={{ item }} state=present
          with_items:
                     - linux-headers-{{ ansible_kernel }}
                     - build-essential
                     - python-passlib

        - name: Install Plugin prerequisites for Ubuntu
          apt: pkg={{ item }} state=present
          with_items:
                     - libssl-dev
                     - dnsutils
                     - fping
                     - libldap2-dev
                     - libpq-dev
                     - libradiusclient-ng-dev
                     - smbclient
                     - gawk

        - name: Create nagcmd group
          group: name=nagcmd state=present

        - name: Create nagios user
          user: name=nagios state=present groups=nagcmd

        - name: Add apache user to nagcmd group
          user: name=www-data state=present groups=nagcmd

        - name: GET Nagios
          get_url: url={{ nagiosurl }} dest={{ ansible_env.HOME }}/nagios/{{ nagiossrc }}.tar.gz

        - name: Get Plugins
          get_url: url={{ pluginsurl }} dest={{ ansible_env.HOME }}/nagios/{{ pluginssrc }}.tar.gz

        - name: Get NRPE
          get_url: url={{ nrpeurl }} dest={{ ansible_env.HOME }}/nagios/{{ nrpesrc }}.tar.gz

        - name: Unpack Nagios source files
          shell: cd {{ ansible_env.HOME }}/nagios && tar -xzvf {{ nagiossrc }}.tar.gz creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}

        - name: Configure
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && ./configure --with-command-group=nagcmd -with-httpd_conf=/etc/apache2/conf-available creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/Makefile

        - name: Make all
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make all creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/base/nagios

        - name: Make install
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install creates=/usr/local/nagios/bin/nagios

        - name: Make install-config
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-config creates=/usr/local/nagios/etc/nagios.cfg

        - name: Make install-commandmode
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-commandmode creates=/usr/local/nagios/var/rw

        - name: Make install-devel
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-devel creates=/usr/local/nagios/include/nagios/nagios.h

        - name: Make install-webconf
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-webconf creates=/etc/apache2/conf-available/nagios.conf

        - name: Activate Nagios site on Ubuntu
          file: src=/etc/apache2/conf-available/nagios.conf dest=/etc/apache2/conf-enabled/nagios.conf state=link owner=root group=root

        - name: Make install-init
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-init creates=/etc/init.d/nagios

        - name: Set htpasswd for nagiosadmin
          htpasswd: path=/usr/local/nagios/etc/htpasswd.users name=nagiosadmin password={{ nagiosadminpass }} state=present

        - name: Unpack Plugin source files
          shell: cd {{ ansible_env.HOME }}/nagios && tar -xzvf {{ pluginssrc }}.tar.gz creates={{ ansible_env['HOME'] }}/nagios/{{ pluginssrc }}

        - name: Configure Plugins
          shell: cd {{ ansible_env.HOME }}/nagios/{{ pluginssrc }} && ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl=/usr/bin/openssl creates={{ ansible_env['HOME'] }}/nagios/{{ pluginssrc }}/Makefile

        - name: Make Plugins
          shell: cd {{ ansible_env.HOME }}/nagios/{{ pluginssrc }} && make creates={{ ansible_env['HOME'] }}/nagios/{{ pluginssrc }}/plugins/check_ping

        - name: Make Install Plugins
          shell: cd {{ ansible_env.HOME }}/nagios/{{ pluginssrc }} && make install creates=/usr/local/nagios/libexec/check_ping

        - name: Unpack NRPE source files
          shell: cd {{ ansible_env.HOME }}/nagios && tar -xzvf {{ nrpesrc }}.tar.gz creates={{ ansible_env['HOME'] }}/nagios/{{ nrpesrc }}

        - name: Configure NRPE
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nrpesrc }} && ./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu creates={{ ansible_env['HOME'] }}/nagios/{{ nrpesrc }}/Makefile

        - name: Make NRPE
          shell: cd {{ ansible_env.HOME }}/nagios/{{ nrpesrc }} && make all creates={{ ansible_env['HOME'] }}/nagios/{{ nrpesrc }}/src/check_nrpe

        - name: Copy check_nrpe
          shell: cp {{ ansible_env['HOME'] }}/nagios/{{ nrpesrc }}/src/check_nrpe /usr/local/nagios/libexec/check_nrpe creates=/usr/local/nagios/libexec/check_nrpe

        - name: Ensure Nagios is started
          service: name=nagios state=started enabled=yes
        
        - name: http service state
          service: name=apache2 state=started enabled=yes

